---
Name: onetime
---
Codem\OneTime\PartialValue:
  min_characters_replaced : 6
  max_characters_replaced : 18
  percent_cleared : 80
  replacement_character: '*'
SilverStripe\ORM\FieldType\DBVarchar:
  extensions:
    - 'Codem\FieldTypes\PartialText'
SilverStripe\ORM\FieldType\DBText:
  extensions:
    - 'Codem\FieldTypes\PartialText'
SilverStripe\ORM\FieldType\DBString:
  extensions:
    - 'Codem\FieldTypes\PartialText'
